### PR TITLE
Deployment improvements and fixes

### PR DESCRIPTION
**Pull request by ColdrickSotK**
This is a set of fixes and improvements to deployment, which allows systems to be deployed when extensions are in subdirectories as is the case in current master of definitions. It also removes the dependency on morphlib now that all the extensions are in definitions.

NOTE: Some of the deployment extensions still depend on morphlib, so only a subset of the deployment extensions will work on a system without morph.

### CODE REVIEW

**Comment by devcurmudgeon** [comment]
On 2015-06-03 11:41, Adam Coldrick wrote:
> This is a set of fixes and improvements to deployment, which allows
> systems to be deployed when extensions are in subdirectories as is 
> the
> case in current master of definitions. It also removes the dependency
> on morphlib now that all the extensions are in definitions.

Thanks!

> NOTE: Some of the deployment extensions still depend on morphlib, so
> only a subset of the deployment extensions will work on a system
> without morph.

Can you be precise, please? Which ones still depend on morphlib, which 
don't?

**Comment by devcurmudgeon** [comment]
Thanks :-)

**Comment by ColdrickSotK** [comment]
> Can you be precise, please? Which ones still depend on morphlib, which
> don't?

**Still dependent on morphlib:**

* distbuild-trove-nfsboot  (.check and .write)
* fstab.configure
* hosts.configure
* jffs2.write
* kvm (.check and .write)
* nfsboot (.check and .write)
* openstack (.check and .write)
* pxeboot (.check and .write)
* rawdisk (.check and .write)
* simple-network.configure
* ssh-rsync  (.check and .write)
* virtualbox-ssh  (.check and .write)

**Not dependent on morphlib:**

* add-config-files.configure
* busybox-init.configure
* ceph.configure
* cloud-init.configure
* distbuild.configure
* image-package.write
* initramfs.write
* install-essential-files.configure
* install-files.configure
* installer.configure
* mason.configure
* moonshot-kernel.configure
* nfsboot-server.configure
* nfsboot.configure
* openstack-*.configure
* sdk.write
* set-hostname.configure
* sshkeys.configure
* strip-gplv3.configure
* sysroot (.write and .check)
* tar (.write and .check)
* trove.configure
* vagrant.configure
* vdaboot.configure

**Comment by devcurmudgeon** [comment]
Great work!

**Pull request merged**
